# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 8088

# mysql
spring:
    datasource:
      url: jdbc:mysql://127.0.0.1:3306/yuzhong_member_system?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
    # jackson时间格式化
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            enabled: true
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    # 指定静态资源的路径
    resources:
        static-locations: classpath:/static/

    thymeleaf:
            #thymeleaf对html的检查过于严格，设置spring.thymeleaf.mode=LEGACYHTML5
        mode: LEGACYHTML5
        cache: false


mybatis:
    configLocation: classpath:mybatis.xml
    typeAliasesPackage: com.huyun.*.model
    mapper-locations: classpath:mapper/**/*.xml
pagehelper:
    helperDialect: mysql
    pagehelper.reasonable: true
    pagehelper.supportMethodsArguments: true
    pagehelper.params: count\=countSql

fs:
  jwt:
    # 加密秘钥
    secret: 24e2e5203c348f86b67cde581c0a9eb5
    # token有效时长，7天，单位秒
    expire: 604800
     # HTTP header自定议参数
    header: APPToken
